# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20161124_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDestacado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=productos.models.img_destacado_upload_to)),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
                ('texto', models.CharField(blank=True, max_length=300, null=True)),
                ('texto_right', models.BooleanField(default=False)),
                ('ver_precio', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
    ]
