# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_productodestacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodestacado',
            name='hacer_img_fondo',
            field=models.BooleanField(default=False),
        ),
    ]
