# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_productodestacado_hacer_img_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodestacado',
            name='texto_color_css',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
